### PR TITLE
RHMAP-6233 - Update mongodb driver (>= 2.1.0) + test node 4.x support

### PR DESCRIPTION
**Pull request by odra**
# Motivation

Update the mongodb dependency version to >=2.1.0.

Tested against node 0.10.43/4.4.5 and mongodb 2.4/2.6/3.3.6 

# Changes

* Updated package.json dependency;
* Modified the server path in unit test to use "application.js" file.

[RHMAP-6233](https://issues.jboss.org/browse/RHMAP-6233)

### CODE REVIEW

**Comment by matzew** [comment]
@david-martin @maleck13 

for Node/Mongo verification bits, which person should be pulled in for reviews?

**Comment by maleck13** [comment]
@matzew I would think most of us could review the change. Not sure there are component owners as such for these service templates

**Comment by maleck13** [comment]
@matzew @odra From a code perspective, this looks fine. I don't see any shrinkwrap, but assume it doesn't have one.

**Comment by matzew** [comment]
@maleck13 I think there is no shrinkwrap - should one be added?

**Comment by maleck13** [comment]
@matzew I would say that is out of scope. I dont see them for any of the templates

**Pull request merged**
